server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: main-server
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: DEBUG

ridg:
  mode: servletRequestListener
  requestId:
    headerName: "X-Request-Id"
    attributeName: "X-Request-Id"
    providingStrategy: auto
    generationDisabled: false
  filter:
    order: 0
  openFeign:
    disableInterceptor: false
  logs:
    mdcKey: "RequestId"